version: '3.8'

services:
    app1:
        image: testdocker:dev
        build: 
            context: .
            dockerfile: TestDocker/Dockerfile
        ports:
            - "5001:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
    app2:
        image: testdocker:dev
        build: 
            context: .
            dockerfile: TestDocker/Dockerfile
        ports:
            - "5002:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
    app3:
        image: testdocker:dev
        build: 
            context: .
            dockerfile: TestDocker/Dockerfile
        ports:
            - "5003:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production